#cloud-config
# Cloud config for application servers

runcmd:
  # Install docker
  - sudo apt-get update
  - sudo apt-get -y install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository 'deb [arch=amd64] https://download.docker.com/linux/ubuntu trusty stable'
  - sudo apt-get update
  - sudo apt-get -y install docker-ce=18.06.1~ce~3-0~ubuntu

  # Run nginx
  - docker run -d -p 80:80 nginx
